name: amaravati_chamber
description: "Amaravati Chamber - A platform for the Amaravati Chamber of Commerce"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  bloc: ^8.1.4
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.13
  formz: ^0.6.1
  get_it: ^7.6.7
  go_router: ^13.1.0
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.3.2
  package_info_plus: ^5.0.1
  settings_ui: ^2.0.2
  supabase: ^2.0.7
  supabase_flutter: ^2.3.2
  url_launcher: ^6.2.4
  freezed_annotation: ^2.4.4
  dartz: ^0.10.1
  http: ^1.1.0
  flutter_html: ^3.0.0-beta.2
  cupertino_icons: ^1.0.2
  html: ^0.15.4
  webview_flutter: ^4.0.0
  youtube_player_iframe: ^4.0.4
  sentry_flutter: ^8.10.1
  logger: ^2.5.0
  flutter_map: ^6.0.0
  flutter_map_pmtiles: ^1.0.4
  latlong2: ^0.9.0
  flutter_map_marker_cluster: ^1.3.0
  vector_map_tiles_pmtiles: ^1.3.0
  vector_map_tiles: ^7.0.0
  flutter_map_heatmap: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.5.7
  build_runner: ^2.4.8
  mockito: ^5.4.4
  bloc_test: ^9.1.7
  injectable_generator:

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/maps/amaravati-outline-polygon.geojson
